core/urls.py
from django .urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('add-expert/', views.add_expert, name="add_expert"),
    path('', views.select_expert, name='select_expert'),
    path('pick-dates/<slug:event_slug>/', views.pick_dates, name='pick_dates'),
    path('confirm-date/<slug:event_slug>/<str:date>/<str:time>/',
          views.confirm_date, name='confirm_date'),
    path('date-confirmed/<slug:event_slug>/',
          views.date_confirmed, name='date_confirmed'),
    path('sending-successful/', views.sending_successful, name="sending_successful"),
    path("view-event/<slug:event_slug>/", views.view_event, name="view_event"),
]

live_session_scheduling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include('django.contrib.auth.urls')),
    path("", include("core.urls"))
]

core/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Expert(models.Model):
    name = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    description = models.CharField(max_length=500)
    contact = models.CharField(max_length=20)
    token = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.name

class Event(models.Model):
    date = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(max_length=128)
    scheduled = models.BooleanField(default=False)
    expert = models.ForeignKey("Expert",
                               on_delete=models.SET_NULL,
                               null=True,
                               related_name="expert_events")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,
                             null=True,
                             related_name="user_events")

    def __str__(self):
        return "Session with " + self.expert.name

core/forms.py
from django import forms
from .models import Expert
class AddExpertForm(forms.ModelForm):
    class Meta:
        model = Expert
        fields = ['name', 'email', 'description', 'contact']


class SelectExpertForm(forms.Form):
    expert_id = forms.IntegerField(widget=forms.HiddenInput())

class PickDatesForm(forms.Form):
    date_1 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'datepicker'
    }))
    time_1 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'timepicker'
    }))
    date_2 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'datepicker'
    }))
    time_2 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'timepicker'
    }))
    date_3 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'datepicker'
    }))
    time_3 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'timepicker'
    }))

class DateTimeConfirmationForm(forms.Form):
    date = forms.CharField(widget=forms.HiddenInput())
    time = forms.CharField(widget=forms.HiddenInput())

core/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import (
    AddExpertForm,
    SelectExpertForm,
    PickDatesForm,
    DateTimeConfirmationForm
    )
from .models import Event, Expert
from uuid import uuid4
from django.core.mail import send_mail
from .utils import get_month_number
from django.utils.timezone import datetime
# Create your views here.
@login_required(login_url='accounts/login')
def select_expert(request):
    form = SelectExpertForm()
    experts = Expert.objects.all()

    if request.method == 'POST':
        form = SelectExpertForm(request.POST)
        if form.is_valid():
            # Create the event
            cd = form.cleaned_data
            expert = Expert.objects.get(pk=cd['expert_id'])
            event = Event.objects.create(
                user=request.user,
                expert=expert,
                slug=uuid4()
            )
            return redirect("core:pick_dates",
                     event_slug=event.slug)

    return render(request, "core/select_expert.html", {
        'form': form,
        'experts': experts,
    })

def pick_dates(request, event_slug):
    form = PickDatesForm()
    event = Event.objects.get(slug=event_slug)
    if request.method == "POST":
        form = PickDatesForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # generate three links and send them
            link_1 = 'http://' + request.get_host() + reverse("core:confirm_date",kwargs={
                'event_slug': event.slug,
                'date': cd['date_1'],
                'time': cd['time_1']
            })
            link_2 = 'http://' + request.get_host() +  reverse("core:confirm_date",kwargs={
                'event_slug': event.slug,
                'date': cd['date_2'],
                'time': cd['time_2']
            })
            link_3 = 'http://' + request.get_host() +  reverse("core:confirm_date",kwargs={
                'event_slug': event.slug,
                'date': cd['date_3'],
                'time': cd['time_3']
            })


            alternative_link = 'http://' + request.get_host() +  reverse("core:pick_dates", kwargs={'event_slug': event.slug})

            message =(
            f"""
                 Hi, Good day to you.
                 Confirm which of the following dates are you available for a live session.
                 {cd['date_1']} at { cd['time_1']}
                 {link_1}

                 {cd['date_2']} at { cd['time_2']}
                 {link_2}

                 {cd['date_3']} at { cd['time_3']}
                 {link_3}

                 If none of the above suit you, select three 3 different dates that suit you.
                 {alternative_link}
                """)
            email_to  = event.expert.email if request.user.is_authenticated else event.expert.user
            send_mail(
                'Live session schedule',
                message,
                settings.DEFAULT_FROM_EMAIL,
                [email_to],
                fail_silently=False
            )

            return redirect('core:sending_successful')

    return render(request, "core/pick_dates.html", {
        'form': form
    })


def sending_successful(request):
    return render(request, "core/sending_successful.html", {})

def confirm_date(request, event_slug, date, time):

    event = Event.objects.get(slug=event_slug)

    data = {
        'date': date,
        'time': time,
    }
    form = DateTimeConfirmationForm(data)

    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data

            # Get the year, month, day from date field
            date_values = cd['date'].split(' ')
            month = get_month_number(date_values[0])
            day = date_values[1].strip(',')
            day = int(day)
            year = int(date_values[2])

            # Get hour and minute from time field
            time_values = cd['time'].strip(' PM').split(':')
            hour = int(time_values[0])
            minute = int(time_values[1])

            # Create the date
            event.date = datetime(year, month, day, hour, minute)
            event.scheduled = True
            event.save()
            event.refresh_from_db()

            # Send email to both parties
            link = 'http://' + request.get_host() + reverse(
                'core:view_event', kwargs={'event_slug': event.slug})
            message = (
                f"""
                Your live session has been successfully scheduled on {event.date}.
                Use the following link to join.
                {link}
                """
            )

            send_mail(
                'Live session has been scheduled',
                message,
                settings.DEFAULT_FROM_EMAIL,
                [event.expert.email, event.user.email],
                fail_silently=False
            )

            return redirect(
                'core:date_confirmed',
                event_slug=event.slug)


    return render(request,"core/confirm_date.html", {
        'event_slug': event.slug,
    })

def date_confirmed(request, event_slug):
    return render(request, "core/date_confirmed.html", {})

def view_event(request, event_slug):
    event = Event.objects.get(slug=event_slug)
    return render(request, "core/view_event.html", {
        'event': event
    })

def add_expert(request):
    form = AddExpertForm()

    if request.method == "POST":
        form = AddExpertForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:select_expert')

    return render(request, "core/add_expert.html", {
        'form': form
    })

core/templates/core/add_expert.html
{% extends "base.html" %}
{% block title %}
Add expert
{% endblock %}
{% block content %}
<div class="container">
    <h1>Add expert</h1>
    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit">Add expert</button>
    </form>
</div>
{% endblock %}

core/templates/core/confirm_date.html
{% extends "base.html" %} {% block content %}
<div class="container">
    <h1>Confirm date</h1>
    <form method="post">
        {% csrf_token %} {{form.as_p}}
        <button type="submit" class="btn waves-effect waves-light">
        Reply: Happy with that
        </button>
    </form>
    <a href="{% url 'core:pick_dates' event_slug %}" class="btn waves-effect waves-light">
        Reply: Nope alt time
    </a>
</div>
{% endblock %}

core/templates/core/date_confirmed.html
{% include "base.html" %} {% block content %}
<div class="container">
    <h1>The time has been set</h1>
</div>
{% endblock %}

core/templates/core/pick_dates.html
{% extends "base.html" %} {% block title %} Pick dates {% endblock %} {% block content %}
<div class="container">
    <h1>Select dates</h1>
    <form method="post">
        {% csrf_token %} {{form.as_p}}
        <button class="btn waves-effect waves-light" type="submit">Send to expert</button>
    </form>
    </form>
</div>
{% endblock %} {% block extra_javascript %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.timepicker');
        options = {}
        var instances = M.Timepicker.init(elems, options);
    });

    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.datepicker');
        options = {}
        var instances = M.Datepicker.init(elems, options);
    });
</script>
{% endblock %}

core/templates/core/select_expert.html
{% extends "base.html" %} {% block title %} Select expert {% endblock %} {% block content %}
<div class="container">
    <h1>Select expert</h1>
    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <select id='select_expert'>
             <option selected >Select expert</option>
             {% for expert in experts %}
               <option value="{{expert.id}}">{{expert.name}}</option>
             {% endfor %}
         </select>
        <button class="btn waves-effect waves-light" type="submit">Select time slots</button>
    </form>
    <a class="btn waves-effect waves-light" href="{% url 'core:add_expert' %}">Add expert</a>
</div>
{% endblock %} {% block extra_javascript %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        options = {

        }
        var instances = M.FormSelect.init(elems, options);
    });
    selectExpert = document.getElementById('select_expert');
    selectExpert.onchange = function selectExpertOnChange(event) {
        document.getElementById('id_expert_id').value = event.target.value;
        console.log('Event fired');
    }
</script>
{% endblock %}

core/templates/core/sending_successful.html
{% extends "base.html" %} {% block content %}
<div class="container">
    <h1>Sent</h1>
    <p>Date and times have been successfully sent to expert email address. </p>
</div>
{% endblock%}

core/templates/core/view_event.html
{% include "base.html" %} {% block content %}
<div class="container">
    <table>
        <tbody>
            <tr>
                <th>Date</th>
                <td>{{event.date}}</td>
            </tr>
            <tr>
                <th>Created by</th>
                <td>{{event.user.username}}</td>
            </tr>
            <tr>
                <th>Expert</th>
                <td>
                    {{event.expert.name}}
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>

<body>
    {% block content %}

    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block extra_javascript %}
    {% endblock %}
</body>

</html>